import { createServerFn } from "@tanstack/react-start";
import { z } from "zod";
import { groundAnalysis } from "./grounding";
const REQUEST_TIMEOUT_MS=120_000;
const AnalyzeInput=z.object({text:z.string().min(40,"Paste at least a few sentences of the document."),title:z.string().optional()});
const AiSchema=z.object({title:z.string().default("Untitled compliance document"),issuer:z.string().default("Unknown issuer"),sourceType:z.enum(["regulatory_notice","card_scheme_bulletin","contract_change","policy_update","internal_comms"]).default("regulatory_notice"),jurisdiction:z.string().default("Not stated"),summary:z.string().default(""),keyPoints:z.array(z.string()).default([]),effectiveDate:z.string().nullable().optional(),deadlines:z.array(z.object({label:z.string(),date:z.string(),type:z.enum(["effective","submission","remediation","notification"]).default("effective")})).default([]),obligations:z.array(z.object({text:z.string(),evidence:z.string().default(""),category:z.string().default("General"),suggestedOwner:z.string().default("Compliance Ops"),dueDate:z.string().nullable().optional()})).default([]),risk:z.object({score:z.number().min(0).max(100).default(50),rationale:z.string().default(""),factors:z.array(z.object({label:z.string(),weight:z.number().default(10),note:z.string().default("")})).default([])}).default({score:50,rationale:"",factors:[]}),owners:z.array(z.object({team:z.string(),reason:z.string().default(""),scope:z.string().default("")})).default([]),plan:z.array(z.object({title:z.string(),detail:z.string().default(""),owner:z.string().default("Compliance Ops"),effort:z.enum(["S","M","L"]).default("M")})).default([]),checklist:z.array(z.object({title:z.string(),owner:z.string().default("Compliance Ops"),dueDate:z.string().nullable().optional()})).default([]),draftResponse:z.string().default(""),confidence:z.object({score:z.number().min(0).max(1).default(.7),rationale:z.string().default("")}).default({score:.7,rationale:""})});
export type AiAnalysis=z.infer<typeof AiSchema>; const MODEL="google/gemini-3.8-flash";
const SYSTEM_PROMPT=`You are ComplyFlow AI, a compliance operations copilot. You are not giving legal advice. Every obligation MUST include evidence copied verbatim from the source; if it cannot be quoted, omit it. Only use calendar dates that appear in the document. Relative timing must remain wording unless anchored by a source date. Risk 80+ requires hard external deadlines plus material regulatory/financial exposure. Produce JSON only matching the requested schema. Summaries, risk, owners and plans are drafts for human review.`;
function extractJson(raw:string):unknown{const fenced=raw.match(/```(?:json)?\s*([\s\S]*?)```/);const c=(fenced?.[1]??raw) as string;const s=c.indexOf("{"),e=c.lastIndexOf("}");if(s===-1||e===-1)throw new Error("The model did not return structured output.");return JSON.parse(c.slice(s,e+1));}
export const analyzeDocument=createServerFn({method:"POST"}).inputValidator((data:unknown)=>AnalyzeInput.parse(data)).handler(async({data}):Promise<AiAnalysis>=>{const apiKey=process.env["LOVABLE_API_KEY"];if(!apiKey)throw new Error("AI is not configured for this deployment. Use the seeded demo documents to explore ComplyFlow.");const document=data.text.slice(0,60000);const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),REQUEST_TIMEOUT_MS);let res:Response;try{res=await fetch("https://ai.gateway.lovable.dev/v1/chat/completions",{method:"POST",signal:controller.signal,headers:{"Content-Type":"application/json",Authorization:`Bearer ${apiKey}`},body:JSON.stringify({model:MODEL,response_format:{type:"json_object"},messages:[{role:"system",content:SYSTEM_PROMPT},{role:"user",content:`${data.title?`Working title: ${data.title}\n\n`:""}Analyse this document and return JSON.\n\n---BEGIN DOCUMENT---\n${document}\n---END DOCUMENT---`}]})});}catch(e){if(e instanceof Error&&e.name==="AbortError")throw new Error("The AI service timed out. Try again, or run the offline engine.");throw e;}finally{clearTimeout(timer)}if(!res.ok){if(res.status===429)throw new Error("The AI service is rate limited right now. Wait a moment and try again.");if(res.status===402)throw new Error("AI credits for this workspace are exhausted. Seeded demo analyses still work.");throw new Error(`Analysis failed (${res.status}). ${(await res.text()).slice(0,200)}`);}const payload=await res.json() as {choices?:{message?:{content?:string}}[]};const content=payload.choices?.[0]?.message?.content;if(!content)throw new Error("The AI service returned an empty response.");return groundAnalysis(AiSchema.parse(extractJson(content)),data.text).analysis;});
