import { createServerFn } from "@tanstack/react-start";
import { z } from "zod";

const TOTAL_BUDGET_MS = 10_000;
const MAX_BYTES = 1_000_000;
const MAX_CHARS = 60_000;
const MAX_REDIRECTS = 3;
const ImportInput = z.object({ url: z.string().min(4, "Enter a public http(s) URL.") });
const NOT_PUBLIC = "That address is not publicly reachable, so it cannot be imported.";

function parseIpv4(host:string):number[]|null { const m=/^(\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})$/.exec(host); if(!m)return null; const p=m.slice(1,5).map(Number); return p.some(n=>Number.isNaN(n)||n<0||n>255)?null:p; }
function isPublicIpv4(p:number[]):boolean { const [a=0,b=0]=p; if(a===0||a===10||a===127||(a===169&&b===254)||(a===172&&b>=16&&b<=31)||(a===192&&b===168)||(a===192&&b===0)||(a===198&&(b===18||b===19))||(a===198&&b===51)||(a===203&&b===0)||(a===100&&b>=64&&b<=127)||a>=224)return false; return true; }
function parseIpv6(host:string):number[]|null { let s=host.toLowerCase(); if(!s.includes(":"))return null; const tail=/(\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3})$/.exec(s); if(tail?.[1]){const v4=parseIpv4(tail[1]);if(!v4)return null;const[a=0,b=0,c=0,d=0]=v4;s=s.slice(0,tail.index)+((a<<8)|b).toString(16)+":"+((c<<8)|d).toString(16);} const halves=s.split("::");if(halves.length>2)return null;const g=(x:string)=>x===""?[]:x.split(":").map(y=>parseInt(y,16));const h=g(halves[0]??""),r=halves.length===2?g(halves[1]??""):[];let groups:number[];if(halves.length===2){const fill=8-h.length-r.length;if(fill<0)return null;groups=[...h,...Array(fill).fill(0),...r];}else groups=h;return groups.length!==8||groups.some(x=>Number.isNaN(x)||x<0||x>0xffff)?null:groups; }
function isPublicIpv6(g:number[]):boolean { const[g0=0,g1=0]=g;if(g.every(x=>x===0)||g.slice(0,7).every(x=>x===0)&&g[7]===1)return false;if(g.slice(0,5).every(x=>x===0)&&(g[5]===0xffff||g[5]===0)){return isPublicIpv4([((g[6]??0)>>8)&255,(g[6]??0)&255,((g[7]??0)>>8)&255,(g[7]??0)&255]);}return !((g0&0xfe00)===0xfc00||(g0&0xffc0)===0xfe80||g0===0x2002||(g0===0x2001&&g1===0x0db8)||(g0===0x2001&&g1===0)||(g0&0xff00)===0xff00); }
function isPublicAddress(ip:string){const h=ip.replace(/^\[|\]$/g,"").replace(/%.*$/,"");const v4=parseIpv4(h);if(v4)return isPublicIpv4(v4);const v6=parseIpv6(h);return v6?isPublicIpv6(v6):false;}
async function resolveWithNodeDns(host:string){try{const dns=await import("node:dns/promises");const r=await dns.lookup(host,{all:true,verbatim:true});const a=r.map(x=>x.address).filter(Boolean);return a.length?a:null;}catch{return null;}}
async function resolveWithDoh(host:string,signal:AbortSignal){const q=async(type:"A"|"AAAA")=>{const res=await fetch(`https://cloudflare-dns.com/dns-query?name=${encodeURIComponent(host)}&type=${type}`,{headers:{accept:"application/dns-json"},signal});if(!res.ok)return[];const body=await res.json() as {Answer?:{type:number;data:string}[]};return(body.Answer??[]).filter(a=>a.type===1||a.type===28).map(a=>a.data.trim());};try{const[a,b]=await Promise.all([q("A"),q("AAAA")]);const x=[...a,...b];return x.length?x:null;}catch{return null;}}
async function assertPublicHop(raw:string,signal:AbortSignal){let url:URL;try{url=new URL(raw.trim());}catch{throw new Error("That does not look like a valid URL.");}if(!["http:","https:"].includes(url.protocol))throw new Error("Only http and https URLs can be imported.");const host=url.hostname.toLowerCase().replace(/^\[|\]$/g,"");if(host==="localhost"||host.endsWith(".localhost")||host.endsWith(".local")||host.endsWith(".internal")||host.endsWith(".home.arpa"))throw new Error(NOT_PUBLIC);if(parseIpv4(host)||parseIpv6(host)){if(!isPublicAddress(host))throw new Error("Private-network addresses cannot be imported.");return url;}if(!host.includes("."))throw new Error(NOT_PUBLIC);const addresses=(await resolveWithDoh(host,signal))??(await resolveWithNodeDns(host));if(!addresses)throw new Error("That hostname could not be resolved safely, so the import was refused.");if(!addresses.every(isPublicAddress))throw new Error("That hostname resolves to a private address, so it cannot be imported.");return url;}
const ENTITIES:Record<string,string>={amp:"&",lt:"<",gt:">",quot:'"',apos:"'",nbsp:" ",mdash:"—",ndash:"–",hellip:"…",rsquo:"’",lsquo:"‘",ldquo:"“",rdquo:"”"};
function decodeEntities(s:string){return s.replace(/&#x([0-9a-f]+);/gi,(_,h:string)=>String.fromCodePoint(parseInt(h,16))).replace(/&#(\d+);/g,(_,d:string)=>String.fromCodePoint(Number(d))).replace(/&([a-z]+);/gi,(m,n:string)=>ENTITIES[n.toLowerCase()]??m);}
function htmlToText(html:string){const tm=/<title[^>]*>([\s\S]*?)<\/title>/i.exec(html);const title=tm?decodeEntities(tm[1]??"").trim().slice(0,160):"";let body=html;const main=/<(article|main)[^>]*>([\s\S]*?)<\/\1>/i.exec(html);if(main?.[2]&&main[2].length>600)body=main[2];const text=decodeEntities(body.replace(/<!--[\s\S]*?-->/g," ").replace(/<(script|style|noscript|svg|template|iframe)[^>]*>[\s\S]*?<\/\1>/gi," ").replace(/<\/(p|div|section|li|tr|h[1-6]|article|header|footer)>/gi,"\n").replace(/<br\s*\/?>/gi,"\n").replace(/<[^>]+>/g," ")).replace(/[ \t\u00a0]+/g," ").replace(/\n{3,}/g,"\n\n").split("\n").map(l=>l.trim()).join("\n").trim();return{title,text};}
export interface UrlImportResult{title:string;text:string;sourceUrl:string;truncated:boolean}
export const importUrl=createServerFn({method:"POST"}).inputValidator((input:unknown)=>ImportInput.parse(input)).handler(async({data}):Promise<UrlImportResult>=>{const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),TOTAL_BUDGET_MS);try{let target=await assertPublicHop(data.url,controller.signal);let res:Response|null=null;for(let hop=0;hop<=MAX_REDIRECTS;hop++){try{res=await fetch(target.toString(),{redirect:"manual",signal:controller.signal,headers:{accept:"text/html,text/plain;q=0.9,*/*;q=0.5","user-agent":"ComplyFlowAI-Import/1.0 (+public page import)"}});}catch{throw new Error("That page could not be fetched within the time limit.");}if(res.status>=300&&res.status<400){const loc=res.headers.get("location");if(!loc)throw new Error("That page returned a redirect with no destination.");if(hop===MAX_REDIRECTS)throw new Error("That page redirected too many times.");target=await assertPublicHop(new URL(loc,target).toString(),controller.signal);continue;}break;}if(!res||!res.ok)throw new Error(`The page responded with ${res?.status??"an error"}. Only publicly readable pages can be imported.`);const type=(res.headers.get("content-type")??"").toLowerCase();if(!type.includes("text/html")&&!type.includes("text/plain"))throw new Error("Only HTML or plain-text pages can be imported. PDFs are not supported yet.");const declared=Number(res.headers.get("content-length")??"0");if(declared>MAX_BYTES)throw new Error("That page is larger than the 1 MB import limit.");if(!res.body)throw new Error("That page returned no readable content.");const reader=res.body.getReader(),chunks:Uint8Array[]=[];let received=0;try{for(;;){const{done,value}=await reader.read();if(done)break;if(!value)continue;received+=value.byteLength;if(received>MAX_BYTES){await reader.cancel().catch(()=>{});throw new Error("That page is larger than the 1 MB import limit.");}chunks.push(value);}}finally{reader.releaseLock();}const merged=new Uint8Array(received);let offset=0;for(const chunk of chunks){merged.set(chunk,offset);offset+=chunk.byteLength;}const raw=new TextDecoder("utf-8").decode(merged);const parsed=type.includes("text/plain")?{title:"",text:raw.trim()}:htmlToText(raw);if(parsed.text.length<40){if(/awsWaf|gokuProps|cf-challenge|__cf_chl|captcha/i.test(raw))throw new Error("That site returned a bot-protection challenge instead of the page. Open it in your browser and paste the text instead.");throw new Error("No readable text could be extracted from that page.");}return{title:parsed.title||target.hostname,text:parsed.text.slice(0,MAX_CHARS),sourceUrl:target.toString(),truncated:parsed.text.length>MAX_CHARS};}finally{clearTimeout(timer);}});