import { createContext,useCallback,useContext,useEffect,useMemo,useState,type ReactNode } from "react";
const STORAGE_KEY="complyflow.organisation.v1";
export interface TeamMapping{category:string;team:string}
export interface OrgProfile{name:string;industry:string;regions:string[];topics:string[];mapping:TeamMapping[]}
export const DEFAULT_ORG:OrgProfile={name:"Meridian Financial Group (illustrative demo organisation)",industry:"Financial services",regions:["European Union"],topics:["Operational resilience","Data protection","Third-party risk"],mapping:[{category:"Incident reporting",team:"Incident Management / Operational Resilience"},{category:"Regulatory communication",team:"Compliance Ops"},{category:"Technical remediation",team:"Technology Operations"},{category:"Third-party changes",team:"Vendor Management"}]};
interface Ctx{profile:OrgProfile;hydrated:boolean;saveProfile:(p:OrgProfile)=>void;resetProfile:()=>void}
const OrgContext=createContext<Ctx|null>(null);
function load():OrgProfile|null{try{const raw=localStorage.getItem(STORAGE_KEY);if(!raw)return null;const p=JSON.parse(raw) as Partial<OrgProfile>;if(!p||typeof p!=="object")return null;return{name:typeof p.name==="string"?p.name:DEFAULT_ORG.name,industry:typeof p.industry==="string"?p.industry:DEFAULT_ORG.industry,regions:Array.isArray(p.regions)?p.regions.filter((r):r is string=>typeof r==="string"):DEFAULT_ORG.regions,topics:Array.isArray(p.topics)?p.topics.filter((t):t is string=>typeof t==="string"):DEFAULT_ORG.topics,mapping:Array.isArray(p.mapping)?p.mapping.filter((m):m is TeamMapping=>!!m&&typeof m.category==="string"&&typeof m.team==="string"):DEFAULT_ORG.mapping};}catch{return null}}
export function OrgProfileProvider({children}:{children:ReactNode}){const[profile,setProfile]=useState(DEFAULT_ORG);const[hydrated,setHydrated]=useState(false);useEffect(()=>{const stored=load();if(stored)setProfile(stored);setHydrated(true)},[]);useEffect(()=>{if(!hydrated)return;try{localStorage.setItem(STORAGE_KEY,JSON.stringify(profile))}catch{}},[profile,hydrated]);const saveProfile=useCallback((p:OrgProfile)=>setProfile(p),[]);const resetProfile=useCallback(()=>setProfile(DEFAULT_ORG),[]);const value=useMemo(()=>({profile,hydrated,saveProfile,resetProfile}),[profile,hydrated,saveProfile,resetProfile]);return <OrgContext.Provider value={value}>{children}</OrgContext.Provider>}
export function useOrgProfile(){const ctx=useContext(OrgContext);if(!ctx)throw new Error("useOrgProfile must be used inside OrgProfileProvider");return ctx}
